// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGT17MFFit8qc_rZpFU99UoMy8pRfL3c',
    appId: '1:939733210624:web:9ff05143796878cfc5eae5',
    messagingSenderId: '939733210624',
    projectId: 'better-muslim-2',
    authDomain: 'better-muslim-2.firebaseapp.com',
    storageBucket: 'better-muslim-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_qzcOUYn_ATkh3Ubuuwh_u2L9uX0vNuc',
    appId: '1:939733210624:android:802b7b9e3e76d9ebc5eae5',
    messagingSenderId: '939733210624',
    projectId: 'better-muslim-2',
    storageBucket: 'better-muslim-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB54zBv88drgIlvRaAiA-0R7m-OaBQ7tU',
    appId: '1:939733210624:ios:6fdfdd578f2c842bc5eae5',
    messagingSenderId: '939733210624',
    projectId: 'better-muslim-2',
    storageBucket: 'better-muslim-2.firebasestorage.app',
    iosBundleId: 'com.bettermuslim.betterMuslim',
  );
}
